server:
  port: 8080
  servlet:
    context-path: /ute

spring:
  mail:
    username: hcmutesending@gmail.com
    password: nbis htol vsck fyav
    properties:
      ®®mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    host: smtp.gmail.com
    port: 587
  datasource:
    url: "jdbc:mysql://localhost:3306/hcmuteforums"
    username: root
    password: 10040109
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "b4ISo6+PT1fY8eppQ564SXabONN945cjuPYa0mTOmPrThHVxEnH7+xxE5RFJCqtk"