server:
  port: 8080
  servlet:
    context-path: /ute

spring:
  multipart:
    max-file-size: 100MB
    max-request-size: 1000MB
  mail:
    username: sending060425@gmail.com
    password: qrwb kauf juku gyqt
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
    host: smtp.gmail.com
    port: 587
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/hcmuteforums}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:  
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6380}
jwt:
  signerKey: "b4ISo6+PT1fY8eppQ564SXabONN945cjuPYa0mTOmPrThHVxEnH7+xxE5RFJCqtk"
upload:
  dir: upload/topics/
  avatar-dir: upload/avatars/
  cover-dir: upload/covers/
logging:
  level:
    or:
      springframework:
        security: DEBUG
        web.socket: DEBUG
