name: Deploy to Dev VPS

on:
  pull_request:
    branches:
      - dev_deploy
    types:
      - closed  # Chỉ khi PR được đóng (đã merge hoặc bị hủy)
    paths:
      - 'backend/**'  # Chỉ chạy khi có thay đổi trong thư mục backend
  push:
    branches:
      - dev_deploy  # Chạy khi có push trực tiếp vào nhánh dev_deploy
    paths:
      - 'backend/**'  # Chỉ chạy khi có thay đổi trong thư mục backend

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)  # Chạy khi push hoặc PR được merge
    name: Deploy Backend to Dev VPS
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Lấy code mới nhất

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Clean Buildx
      run: |
        docker buildx prune
        docker buildx create --use --name mybuilder

    - name: Build Docker Image
      working-directory: ./backend
      run: |
        echo "Building new image..."
        docker compose build --progress=plain hcmuteforums

    - name: Deploy using Docker Compose
      working-directory: ./backend
      run: |
        docker compose down
        docker compose up -d --no-build

    - name: Clean up old images
      run: |
        docker image prune -a -f --filter "label!=maintainer=actions-runner"
